
# Gimme some space
add_newline = true

[aws]
disabled = true

# default prompt character
[character]
disabled = true  # disable to use xonsh shell

[cmd_duration]
disabled = true

[git_branch]
format = "[â‡’](bold green) [$symbol$branch]($style) "
symbol = "ğŸŒ±"

[git_status]
format="$all_status"
deleted = "[âœ˜](red)"
modified = "ğŸ”¸"
staged= "âœ”"
untracked = "?"

[hostname]
format = "[$hostname]($style) "

[jobs]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true

[rust]
format = "$symbol($style)"

[shell]
bash_indicator = ""
powershell_indicator ="PS "
xonsh_indicator = "ğŸš "
format="[$indicator](blue)"
disabled = false

[username]
disabled = true
