
# Gimme some space
add_newline = true

[cmd_duration]
disabled = true

[git_branch]
format = "[â‡’](bold green) [$symbol$branch]($style) "
symbol = "ðŸŒ± "

[git_status]
format="$all_status"
deleted = "[âœ˜](red)"
modified = "ðŸ”¸"
staged= "âœ”"
untracked = "?"

[hostname]
format = "[$hostname]($style) "

[jobs]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true

[rust]
format = "$symbol($style)"

[username]
disabled = true
